name: "Pull Request Labeler"
on:
  - pull_request_target

permissions: read-all # default for workflow

jobs:
  triage:
    permissions:
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # pin@v5
        with:
          dot: true
